### ISSUE TITLE
shortcuts

### ISSUE THREAD

**Issue by darkzbaron** [gregsadetsky/email-dictation#1]
hey, i love your extension. Thanks for the great work. What is the quickest way to implement keyboard shortcut?
I have tried the below to no avail. 
document.querySelector(".gmde_microphone")
        .dispatchEvent(new MouseEvent("mousedown"));

Thanks,Jonathan

**Comment by gregsadetsky** [comment]
Hey Jonathan, Thanks for the nice words!

Try `document.querySelector(".gmde_microphone").click()` and let me know if that works.

What are you using to create the keyboard shortcut? Another Chrome extension? Are you extending this extension?

Cheers

**Comment by darkzbaron** [comment]
It was badly needed really. I can't imagine how i could live without. It works perfect by the way. 

Here it is https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck

You can basically run javascript with keyboard shortcuts. It is fairly reliable!

Also, would you know of anyway to extend the speech to text to any text field in chrome? Would it be complicated to do?

I am looking forward to hear back from you. 

Cheers

**Comment by gregsadetsky** [comment]
Thanks for the link to Shortkeys!

It would probably be better to create another, more generic, extension that would allow you to dictate into any field (not just Gmail). It's a great idea though -- I'll keep it in mind!

**Comment by darkzbaron** [comment]
cool! Let me know. iwill also look into it
