### ISSUE TITLE
Thanks for this extension and a question

### ISSUE THREAD

**Issue by matanster** [gregsadetsky/email-dictation#3]
Hi,

This is an elegant extension cobbling together the various API with clean simple usability. I am wondering where does the speech API quota for it comes from, as google seem to require payment beyond a duration that this extension can't possibly suffice with. Perhaps you can comment.

Thanks!

**Comment by gregsadetsky** [comment]
Thanks for the kind words!

The extension uses Chrome's built-in _Web Speech API_. From what I understand -- see [here](https://groups.google.com/a/chromium.org/d/msg/chromium-dev/TJRsxtxkB_Y/jaCX307c1tQJ) for a discussion on the topic -- there is no quota on this built-in functionality. In this regards, it's different than the (commercial) Speech API provided by Google.

Cheers

Greg
